//TABLA EMBEBIDA
--CREATE TABLE CLIENTES(
--    ID_CLIENTE NUMBER,
--    NOMBRE NVARCHAR2(50),
--    DIRECCION NVARCHAR2(100),
--    CONTACTO NUMBER(10),
--    CONSTRAINT ID_CLIENTE PRIMARY KEY (ID_CLIENTE)
--);

--CREATE SEQUENCE S_ID_CLIENTES
--START WITH 1
--INCREMENT BY 1
--NOCACHE NOCYCLE;

//DATA
--INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, DIRECCION, CONTACTO)
--VALUES (001, 'John Doe','No address',0000000000);
--
--INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, DIRECCION, CONTACTO)
--VALUES (002, 'Jane Doe','No address',0000000001);
--
--INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, DIRECCION, CONTACTO)
--VALUES (003, 'Tyler Durden','No address',0000000002);
----------------------------------------------------------------------------------------------------------
CREATE TABLE MASCOTA(
    ID_MASCOTA NUMBER,
    NOMBRE NVARCHAR2(15),
    RAZA NVARCHAR2(15),
    EDAD NUMBER,
    RAZON_CITA NVARCHAR2(100),
    CLIENTE_ID NUMBER,
    RESPONSABLE_ID NUMBER,
    VETERINARIA_ID NUMBER,
    CONSTRAINT ID_MASCOTAS PRIMARY KEY (ID_MASCOTA)
);

INSERT INTO MASCOTA VALUES(1,'PUSHEEN','CALLEJERO',5,'PRUEBA',1,1,1000);
INSERT INTO MASCOTA VALUES('PUSHEEN I','CALLEJERO',5,'PRUEBA',1,1,1000);
INSERT INTO MASCOTA VALUES('PUSHEEN II','CALLEJERO',5,'PRUEBA',1,1,1000);
INSERT INTO MASCOTA VALUES('PUSHEEN III','CALLEJERO',5,'PRUEBA',1,1,1000);
INSERT INTO MASCOTA VALUES('PUSHEEN IV','CALLEJERO',5,'PRUEBA',1,1,1000);

CREATE SEQUENCE S_ID_MASCOTA
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

SELECT * FROM MASCOTA;
DELETE FROM MASCOTA WHERE ID_MASCOTA=25;

CREATE TABLE RESPONSABLE(
    ID_RESPONSABLE NUMBER,
    NOMBRE NVARCHAR2(50),
    CONTACTO NUMBER(10),
    VETERINARIA_ID NUMBER,
    CONSTRAINT ID_RESPONSABLES PRIMARY KEY (ID_RESPONSABLE)
);

CREATE SEQUENCE S_ID_RESPONSABLE
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

INSERT INTO RESPONSABLE VALUES(5,'J ',2222222222,1001);
SELECT * FROM RESPONSABLE;
DELETE FROM RESPONSABLE WHERE ID_RESPONSABLE=1000;

//TABLA EMBEBIDA
//TABLA BASE
--CREATE TABLE VETERINARIA(
--    ID_VETERINARIA NUMBER,
--    NOMBRE NVARCHAR2(50),
--    DIRECCION NVARCHAR2(50),
--    TELEFONO NUMBER(10),
--    CONSTRAINT ID_VETERINARIA PRIMARY KEY (ID_VETERINARIA)
--);

--CREATE SEQUENCE S_ID_VETERINARIA
--START WITH 1
--INCREMENT BY 1
--NOCACHE NOCYCLE;

--INSERT INTO VETERINARIA (ID_VETERINARIA,NOMBRE,DIRECCION,TELEFONO)
--VALUES(1000,'MedicanDog','Libertad',1000000000);
--
--INSERT INTO VETERINARIA (ID_VETERINARIA,NOMBRE,DIRECCION,TELEFONO)
--VALUES(1001,'Vet','No address',1000000001);
---------------------------------------------------------------------------------------------------------

COMMIT;