--ELIMINACION DE LA TABLA SI EXISTE UNA PREVIA
DROP TABLE IF EXISTS VETERINARIA;

--CREACION DE LA TABLA
CREATE TABLE VETERINARIA(
    ID_VETERINARIA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE NVARCHAR2(50),
    DIRECCION NVARCHAR2(50),
    TELEFONO NUMBER(10),
    CONSTRAINT ID_VETERINARIA PRIMARY KEY (ID_VETERINARIA)
 );